# Generated by Django 5.0.3 on 2024-07-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
    ]
