# Generated by Django 5.0.3 on 2024-09-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
